mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
#from blog.views import index, show_genres, post_list

from blog.views import CategoryListView
from books.views import BookListView
from gesfi.views import *

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    #### Blog #######
#    url(r'^$', 'blog.views.index'),
    url(r'^genres/$', 'blog.views.show_genres'),
    url(r'^blog/', 'blog.views.post_list'),
    url(r'^meta/', 'blog.views.display_meta'),
    url(r'^time/$', 'blog.views.current_datetime'),
    url(r'^time/plus/(\d{1,2})/$', 'blog.views.hours_ahead'),
    url(r'^products/$', CategoryListView.as_view()),
    url(r'^some_view/$','blog.views.some_view'),

    #### Books #######
#    url(r'^search-form/$', 'books.views.search_form'),
    url(r'^search/$', 'books.views.search'),
    url(r'^contact/$', 'books.views.contact'),
    url(r'^books/$', BookListView.as_view()),

    #### GesFi #######
    url(r'^$', 'gesfi.views.main_page'),
    url(r'^user/(\w+)/$', user_page),
    url(r'^transactions/(\w+)/$', transactions_page),
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', logout_page),

]

books/models.py
from django.db import models

# Create your models here.
from django.db import models

class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    email = models.EmailField()

    def __str__(self):
        return u'%s %s' % (self.first_name, self.last_name)

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher)
    publication_date = models.DateField()

    def __str__(self):
        return self.title

books/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    email = forms.EmailField(required=False, label='Your e-mail address')
    message = forms.CharField(widget=forms.Textarea)

    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError("Not enough words!")
        return message

books/views.py
from django.shortcuts import render
from . forms import ContactForm
from django.http import HttpResponse
from django.core.mail import send_mail

from books.models import Book

# Create your views here.

#def search_form(request):
#    return render(request, 'search_form.html')


def search(request):
    errors = []
    if 'q' in request.GET:
        q = request.GET['q']
        if not q:
            errors.append('Enter a search term.')
        elif len(q) > 20:
            errors.append('Please enter at most 20 characters.')
        else:
            books = Book.objects.filter(title__icontains=q)
            return render(request, 'search_results.html',
                {'books': books, 'query': q})
    return render(request, 'search_form.html',
        {'errors': errors})

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            send_mail(
                cd['subject'],
                cd['message'],
                cd.get('email', 'noreply@example.com'),
                ['siteowner@example.com'],
            )
            return HttpResponseRedirect('/contact/thanks/')
    else:
        form = ContactForm(
            initial={'subject': 'I love your site!'}
        )
    return render(request, 'contact_form.html', {'form': form})


from django.views.generic import ListView

#############################################################################################
class BookListView(ListView):
    model = Book

    def head(self, *args, **kwargs):
        last_book = self.get_queryset().latest('publication_date')
        response = HttpResponse('')
        # RFC 1123 date format
        response['Last-Modified'] = last_book.publication_date.strftime('%a, %d %b %Y %H:%M:%S GMT')
        return response

books/templates/book_list.html
{% extends "base.html" %}

{% block title %}Book list{% endblock %}

{% block content %}
    <br>
      <h1>Book List Title</h1>
    <br>

{% endblock %}

books/templates/contact_form.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <title>Contact us</title>
</head>
<body>
    <h1>Contact us</h1>

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" method="post">
        <div class="field">
            {{ form.subject.errors }}
            <label for="id_subject">Subject:</label>
            {{ form.subject }}
        </div>
        <div class="field">
            {{ form.email.errors }}
            <label for="id_email">Your e-mail address:</label>
            {{ form.email }}
        </div>
        <div class="field">
            {{ form.message.errors }}
            <label for="id_message">Message:</label>
            {{ form.message }}
        </div>
        <input type="submit" value="Submit">
    </form>
</body>
</html>

books/templates/search_form.html
{% extends "base.html" %}

{% block title %}Book search{% endblock %}

{% block content %}
    <br>

    <form action="" method="get">
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form>

    {% if errors %}
        <ul>
            {% for error in errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <br>

{% endblock %}

books/templates/search_results.html
{% extends "base.html" %}

{% block title %}Book search{% endblock %}

{% block content %}

    <p>You searched for: <strong>{{ query }}</strong></p>

    {% if books %}
        <p>Found {{ books|length }} book{{ books|pluralize }}.</p>
        <ul>
            {% for book in books %}
            <li>{{ book.title }}
                    <br>
                    written by: {{ book.authors.first_name}} {{ book.authors.last_name}}
                    <br>
                    and published by: {{ book.publisher}}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No books matched your search criteria.</p>
    {% endif %}

{% endblock %}